eureka:
  client:
    service-url:
      defaultZone: http://service-reg:8761/eureka
name:
  value: CEcom
spring:
  cloud:
    config:
      override-system-properties: false
  zipkin:
    base-url: http://zipkin:9411

